# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       kmod

# >> macros
# << macros

Summary:    Linux kernel module handling
Version:    9
Release:    1
Group:      Kernel/Linux Kernel
License:    LGPLv2
URL:        http://git.profusion.mobi/cgit.cgi/kmod.git/
Source0:    http://www.kernel.org/pub/linux/utils/kernel/kmod/%{name}-%{version}.tar.xz
Source100:  kmod.yaml
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(liblzma)
Provides:   module-init-tools > 3.15
Obsoletes:   module-init-tools <= 3.15

%description
kmod is a set of tools to handle common tasks with Linux kernel modules like
insert, remove, list, check properties, resolve dependencies and aliases.


%package devel
Summary:    Devel files for libkmod
Group:      Kernel/Linux Kernel
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-libs = %{version}-%{release}

%description devel
Development files for libkmod.

%package libs
Summary:    Libraries for kmod
Group:      Kernel/Linux Kernel
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libs
Libraries for kmod.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --with-xz \
    --with-zlib

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
mkdir -p $RPM_BUILD_ROOT%{_sbindir}/
ln -sf ../bin/kmod $RPM_BUILD_ROOT%{_sbindir}/modprobe
ln -sf ../bin/kmod $RPM_BUILD_ROOT%{_sbindir}/modinfo
ln -sf ../bin/kmod $RPM_BUILD_ROOT%{_sbindir}/insmod
ln -sf ../bin/kmod $RPM_BUILD_ROOT%{_sbindir}/rmmod
ln -sf ../bin/kmod $RPM_BUILD_ROOT%{_sbindir}/depmod
ln -sf ../bin/kmod $RPM_BUILD_ROOT%{_sbindir}/lsmod

mkdir -p $RPM_BUILD_ROOT%{_sysconfdir}/modprobe.d
mkdir -p $RPM_BUILD_ROOT%{_sysconfdir}/depmod.d
mkdir -p $RPM_BUILD_ROOT%{_prefix}/lib/modprobe.d
# << install post


%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_bindir}/kmod
%{_mandir}/*
%{_sbindir}/modprobe
%{_sbindir}/modinfo
%{_sbindir}/insmod
%{_sbindir}/rmmod
%{_sbindir}/lsmod
%{_sbindir}/depmod
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/libkmod.h
%{_libdir}/libkmod.so
%{_libdir}/pkgconfig/libkmod.pc
# >> files devel
# << files devel

%files libs
%defattr(-,root,root,-)
%{_libdir}/libkmod.so.*
# >> files libs
# << files libs
